In [1]:
import pandas as pd
import numpy as np

In [2]:
week1=pd.read_csv('C:/Users/brady/OneDrive/Documents/R-Baseball-Stuff/NFL/tracking_week_1.csv')
week2=pd.read_csv('C:/Users/brady/OneDrive/Documents/R-Baseball-Stuff/NFL/tracking_week_2.csv')
week3=pd.read_csv('C:/Users/brady/OneDrive/Documents/R-Baseball-Stuff/NFL/tracking_week_3.csv')
week4=pd.read_csv('C:/Users/brady/OneDrive/Documents/R-Baseball-Stuff/NFL/tracking_week_4.csv')
week5=pd.read_csv('C:/Users/brady/OneDrive/Documents/R-Baseball-Stuff/NFL/tracking_week_5.csv')
week6=pd.read_csv('C:/Users/brady/OneDrive/Documents/R-Baseball-Stuff/NFL/tracking_week_6.csv')
week7=pd.read_csv('C:/Users/brady/OneDrive/Documents/R-Baseball-Stuff/NFL/tracking_week_7.csv')
week8=pd.read_csv('C:/Users/brady/OneDrive/Documents/R-Baseball-Stuff/NFL/tracking_week_8.csv')
week9=pd.read_csv('C:/Users/brady/OneDrive/Documents/R-Baseball-Stuff/NFL/tracking_week_9.csv')

In [4]:
play_result = pd.read_csv('C:/Users/brady/OneDrive/Documents/R-Baseball-Stuff/NFL/plays.csv')

In [5]:
tackles = pd.read_csv('C:/Users/brady/OneDrive/Documents/R-Baseball-Stuff/NFL/tackles.csv')

In [6]:
play_result.columns

Index(['gameId', 'playId', 'ballCarrierId', 'ballCarrierDisplayName',
       'playDescription', 'quarter', 'down', 'yardsToGo', 'possessionTeam',
       'defensiveTeam', 'yardlineSide', 'yardlineNumber', 'gameClock',
       'preSnapHomeScore', 'preSnapVisitorScore', 'passResult', 'passLength',
       'penaltyYards', 'prePenaltyPlayResult', 'playResult',
       'playNullifiedByPenalty', 'absoluteYardlineNumber', 'offenseFormation',
       'defendersInTheBox', 'passProbability', 'preSnapHomeTeamWinProbability',
       'preSnapVisitorTeamWinProbability', 'homeTeamWinProbabilityAdded',
       'visitorTeamWinProbilityAdded', 'expectedPoints', 'expectedPointsAdded',
       'foulName1', 'foulName2', 'foulNFLId1', 'foulNFLId2'],
      dtype='object')

In [7]:
tackles

,gameId,playId,nflId,tackle,assist,forcedFumble,pff_missedTackle
0,2022090800,101,42816,1,0,0,0
1,2022090800,393,46232,1,0,0,0
2,2022090800,486,40166,1,0,0,0
3,2022090800,646,47939,1,0,0,0
4,2022090800,818,40107,1,0,0,0
...,...,...,...,...,...,...,...
17421,2022091113,2494,43533,0,0,0,1
17422,2022092502,3510,42406,0,0,0,1
17423,2022091113,3642,43478,0,0,0,1
17424,2022091901,3578,42431,0,0,0,1
17425,2022091901,3845,46199,0,0,0,1

In [8]:
play_result= play_result[['gameId', 'playId', 'ballCarrierId', 'ballCarrierDisplayName',
       'playDescription', 'quarter', 'down', 'yardsToGo', 'possessionTeam',
       'defensiveTeam', 'gameClock', 'passResult',
       'preSnapHomeScore', 'preSnapVisitorScore','playResult',
       'playNullifiedByPenalty','expectedPoints', 'expectedPointsAdded']]

In [9]:
all_weeks = pd.concat([week1,week2,week3,week4,week5,week6,week7,week8,week9])

In [17]:
#all_weeks.loc[all_weeks['nflId']==all_weeks.isna()]

In [11]:
all_weeks = all_weeks.merge(right=play_result,how='outer', on=['gameId','playId'])

In [12]:
all_weeks = all_weeks.loc[all_weeks['passResult']!='S']

In [13]:
all_weeks = all_weeks.loc[all_weeks['playNullifiedByPenalty']!='Y']

In [14]:
all_weeks = all_weeks.drop(columns=['playNullifiedByPenalty','passResult'])

In [16]:
#all_weeks.to_csv('all_weeks.csv', index = True)

In [ ]:
all_weeks[['gameId','playId','frameId','displayName']].groupby(['gameId','playId','frameId'], as_index=False).count()

In [18]:
all_weeks = all_weeks.merge(right=tackles,how='outer', on=['gameId','playId','nflId'])

In [21]:
all_weeks.loc[all_weeks['pff_missedTackle']==1]

,gameId,playId,nflId,displayName,frameId,time,jerseyNumber,club,playDirection,x,...,gameClock,preSnapHomeScore,preSnapVisitorScore,playResult,expectedPoints,expectedPointsAdded,tackle,assist,forcedFumble,pff_missedTackle
23252,2022090800,1102,52492.0,Terrell Lewis,1.0,2022-09-08 21:03:51.299999,52.0,LA,right,88.01,...,9:37,0.0,7.0,2.0,3.894043,-0.132479,0.0,0.0,0.0,1.0
23253,2022090800,1102,52492.0,Terrell Lewis,2.0,2022-09-08 21:03:51.400000,52.0,LA,right,87.85,...,9:37,0.0,7.0,2.0,3.894043,-0.132479,0.0,0.0,0.0,1.0
23254,2022090800,1102,52492.0,Terrell Lewis,3.0,2022-09-08 21:03:51.500000,52.0,LA,right,87.65,...,9:37,0.0,7.0,2.0,3.894043,-0.132479,0.0,0.0,0.0,1.0
23255,2022090800,1102,52492.0,Terrell Lewis,4.0,2022-09-08 21:03:51.599999,52.0,LA,right,87.41,...,9:37,0.0,7.0,2.0,3.894043,-0.132479,0.0,0.0,0.0,1.0
23256,2022090800,1102,52492.0,Terrell Lewis,5.0,2022-09-08 21:03:51.700000,52.0,LA,right,87.14,...,9:37,0.0,7.0,2.0,3.894043,-0.132479,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11859322,2022091101,382,46162.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0
11859323,2022091101,489,46124.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0
11859324,2022091101,489,42470.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0
11859325,2022091109,91,43313.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0
11859326,2022091109,1358,53503.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0

In [22]:
all_weeks.to_csv('all_weeks_miss.csv', index = True)